name: Deploy to wiki.daxa.dev
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "22"

        - name: Clone Starlight Wiki Template
          run: |
            git clone https://github.com/learndaxa/StarlightWiki.git ../StarlightWiki/

        - name: Copy Wiki Pages
          run: |
            mkdir -p ../StarlightWiki/src/content/docs/
            cp -r ./docs/* ../StarlightWiki/src/content/docs/

        - name: 'Create ENV File'
          run: |
            touch ../StarlightWiki/.env
            echo VITE_TITLE="Tutorial" >> ../StarlightWiki/.env
            echo VITE_SITE_URL="https://wiki.daxa.dev" >> ../StarlightWiki/.env
            echo VITE_GITHUB_URL="https://github.com/learndaxa/Wiki" >> ../StarlightWiki/.env
            echo VITE_DISCORD_INVITE="https://discord.gg/mZrUeJfxB8" >> ../StarlightWiki/.env
            echo VITE_GITHUB_EDIT_LINK="https://github.com/learndaxa/Tutorial/edit/main/docs/" >> ../StarlightWiki/.env

        - name: Building Static Site
          run: |
            cd ../StarlightWiki/
            npm install
            npm run astro build

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: "../StarlightWiki/dist/"

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1