name: Deploy to wiki.learndaxa.com
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "20"

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.12"

        - name: Clone Repos
          run: |
            git clone https://${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}@github.com/learndaxa/WebsiteTemplate.git ../WebsiteTemplate/
            git clone https://${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}@github.com/learndaxa/WebsiteRenderer.git ../WebsiteRenderer/

        - name: Install Python dependencies
          run: |
            pip install -r WebsiteRenderer/requirements.txt

        - name: Rendering Markdown to Svelte
          run: |
            python ../WebsiteRenderer/main.py --goal wiki --source "docs/" --destination "../WebsiteTemplate/src/routes/"

        - name: Building Static Site
          run: |
            cd ../WebsiteTemplate/
            npm install
            npm run build

        - name: Making static links
          run: |
            cd ../
            python WebsiteRenderer/fix.py --destination "WebsiteTemplate/" --domain "https://wiki.learndaxa.com"

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: "../WebsiteTemplate/build/"
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1